### ISSUE TITLE
Bad values in USGS CMG TimeSeries file on THREDDS server

### ISSUE THREAD

**Issue by kwilcox** [axiom-data-science/usgs-cmg-portal#35]
@rsignell-usgs @emontgomery-usgs

Project: MBAY_LT
File:  6112cs-a.nc

The time values in the beginning of the file seem incorrect:

time = 6, 5, 1, 1667329119, -1072647888, 1140850688, 72030414, 6, 5, 
    1398748208, 3, 4, 1392508928, 1694498816, 1313428569, 538976288, 
    1919509343, 1935764480, 1718579821, 1714499630, 1929379840, 9, 4, 
    1936027251, 1, 1836412160, 7, 1, 1683976801, 0, 1817600364, 2040140556, 
    2037409024, 1114206820, 1936028265, 2, 4, 1110016792, ... from here on they look good

**Comment by emontgomery-usgs** [comment]
This was one of the two you found back in Nov, and I fixed and replaced on
the server.   Did you download again or are you working from files on your
disk?

If you did a fresh download, perhaps the repaired versions were over
written by an older back-up.  Let me investigate.

On Thu, Jan 22, 2015 at 5:04 PM, Kyle Wilcox <notifications@github.com>
wrote:

> @rsignell-usgs <https://github.com/rsignell-usgs> @emontgomery-usgs
> <https://github.com/emontgomery-usgs>
>
> Project: MBAY_LT
> File: 6112cs-a.nc
>
> The time values in the beginning of the file seem incorrect:
>
> time = 6, 5, 1, 1667329119, -1072647888, 1140850688, 72030414, 6, 5,
> 1398748208, 3, 4, 1392508928, 1694498816, 1313428569, 538976288,
> 1919509343, 1935764480, 1718579821, 1714499630, 1929379840, 9, 4,
> 1936027251, 1, 1836412160, 7, 1, 1683976801, 0, 1817600364, 2040140556,
> 2037409024, 1114206820, 1936028265, 2, 4, 1110016792, ... from here on
> they look good
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/axiom-data-science/usgs-cmg-portal/issues/35>.
>



-- 
Ellyn Montgomery, Oceanographer and Data Manager
U.S. Geological Survey
Woods Hole Coastal and Marine Science Center
384 Woods Hole Rd., Woods Hole, MA, 02543-1598
(508) 457-2356

**Comment by kwilcox** [comment]
They are bad on the THREDDS server: http://geoport.whoi.edu/thredds/dodsC/usgs/data2/emontgomery/stellwagen/Data/MBAY_LT/6112cs-a.nc.ascii?time[0:1:7019]

**Comment by emontgomery-usgs** [comment]
This is really odd.  The file on my machine that I fixed and put onto
geoport in November once again has the dates wrong.   Starting to
diagnose.  Will let you know when another set of "fixed" files is back up.


On Fri, Jan 23, 2015 at 9:39 AM, Kyle Wilcox <notifications@github.com>
wrote:

> They are bad on the THREDDS server:
> http://geoport.whoi.edu/thredds/dodsC/usgs/data2/emontgomery/stellwagen/Data/MBAY_LT/6112cs-a.nc.ascii?time[0:1:7019]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/axiom-data-science/usgs-cmg-portal/issues/35#issuecomment-71201932>
> .
>



-- 
Ellyn Montgomery, Oceanographer and Data Manager
U.S. Geological Survey
Woods Hole Coastal and Marine Science Center
384 Woods Hole Rd., Woods Hole, MA, 02543-1598
(508) 457-2356

**Comment by emontgomery-usgs** [comment]
6112cs-a.nc is repaired and the link above shows reasonable time data.

Thanks and have a nice weekend!

On Fri, Jan 23, 2015 at 9:39 AM, Kyle Wilcox <notifications@github.com>
wrote:

> They are bad on the THREDDS server:
> http://geoport.whoi.edu/thredds/dodsC/usgs/data2/emontgomery/stellwagen/Data/MBAY_LT/6112cs-a.nc.ascii?time[0:1:7019]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/axiom-data-science/usgs-cmg-portal/issues/35#issuecomment-71201932>
> .
>



-- 
Ellyn Montgomery, Oceanographer and Data Manager
U.S. Geological Survey
Woods Hole Coastal and Marine Science Center
384 Woods Hole Rd., Woods Hole, MA, 02543-1598
(508) 457-2356

**Comment by rsignell-usgs** [comment]
I reconverted the new files to CF-1.6 and the start/stop times look good:
![1-23-2015 5-09-07 pm](https://cloud.githubusercontent.com/assets/1872600/5883671/a6d9782e-a322-11e4-839c-ba3cef3d1c58.png)
Woo hoo!
