### ISSUE TITLE
Make pycsw and sciwms endpoints accessible by outside world

### ISSUE THREAD

**Issue by rsignell-usgs** [axiom-data-science/usgs-cmg-portal#36]
Right now the `pycsw` endpoint at `http://geoport.whoi.edu:8000` and the `sciwms` endpoint at `http://geoport.whoi.edu:8899` are only accessible internally.

We need to make them accessible to the outside world as:
```
pycsw.geoport.whoi.edu
sciwms.geoport.whoi.edu
```

**Comment by rsignell-usgs** [comment]
Okay, struggling a bit here.   We've got pycsw accessible to the world here:
http://geoport.whoi.edu/csw?service=CSW&version=2.0.2&request=GetCapabilities
but my simple ipython notebook test is failing in cell [8]:  http://nbviewer.ipython.org/gist/rsignell-usgs/58f80172a77b8182843f/usgs_pycsw.ipynb

On another pycsw server, essentially the same test is working fine: 
http://nbviewer.ipython.org/gist/rsignell-usgs/58f80172a77b8182843f/comt_pycsw.ipynb

@tomkralidis, any ideas?

**Comment by kalxas** [comment]
@rsignell-usgs can you please check the url setting in the configuration file? It should not be localhost

**Comment by rsignell-usgs** [comment]
Guys, it's working now!
http://nbviewer.ipython.org/gist/rsignell-usgs/58f80172a77b8182843f/usgs_pycsw.ipynb
@kwilcox, can you try doing a csw search on 'CMG_Portal` as in the notebook here and consuming the WMS service?

**Comment by tomkralidis** [comment]
cc @smrazgs

Hooray for defined and actionable link types - awesome!

**Comment by kwilcox** [comment]
Opened https://github.com/axiom-data-science/usgs-cmg-portal/issues/41 to track the consumption of the service
