### ISSUE TITLE
Dropped epic code and variables in this dataset

### ISSUE THREAD

**Issue by rsignell-usgs** [axiom-data-science/usgs-cmg-portal#38]
in the original data here:
http://stellwagen.er.usgs.gov/thredds/dodsC/TSdata/ARGO_MERCHANT/1211P-A.cdf.html
we have variables `P_4022, P_4023 and P_4020`, while in the CF-1.6 version here:
http://geoport.whoi.edu/thredds/dodsC/usgs/data2/emontgomery/stellwagen/CF-1.6/ARGO_MERCHANT/1211P-A.cdf.html
we only have `P`.   Why did the other pressure variables get dropped and why did the epic code get dropped from the name?

**Comment by kwilcox** [comment]
Fixed in https://github.com/axiom-data-science/usgs-cmg-portal/commit/fcdaa13fceccfc4c5c40f6e01680b902d01300cb
