### ISSUE TITLE
hourly-averaged data files

### ISSUE THREAD

**Issue by rsignell-usgs** [axiom-data-science/usgs-cmg-portal#39]
After conversion to CF-1.6, all the hourly-averaged data files seem to be missing, the ones ending with `-A1H`.   
For example, compare these two directories:

INPUT: http://geoport.whoi.edu/thredds/catalog/usgs/data2/emontgomery/stellwagen/Data/PONCHARTRAIN/catalog.html

OUTPUT:
http://geoport.whoi.edu/thredds/catalog/usgs/data2/emontgomery/stellwagen/CF-1.6/PONCHARTRAIN/catalog.html

Was this intentional, with the idea that the hourly data could always be calculated from higher-frequency data?

**Comment by kwilcox** [comment]
This was intentional, we are skipping them via the download regex: https://github.com/axiom-data-science/usgs-cmg-portal/blob/master/woods_hole_obs_data/collect.py#L178

**Comment by rsignell-usgs** [comment]
Okay, I just spoke with @emontgomery-usgs and we are okay omitting these, as they can be derived from the original data.   We can revisit later if there are performance or other issues.
